//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodePrinter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodePrinter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto EAN13 / Code 128.
        /// </summary>
        internal static string AutoEAN13Code128 {
            get {
                return ResourceManager.GetString("AutoEAN13Code128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code 128.
        /// </summary>
        internal static string Code128 {
            get {
                return ResourceManager.GetString("Code128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN 13.
        /// </summary>
        internal static string EAN13 {
            get {
                return ResourceManager.GetString("EAN13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HelpBarcodePrint {
            get {
                object obj = ResourceManager.GetObject("HelpBarcodePrint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///N
        ///OD
        ///q344
        ///Q192,24
        ///D15
        ///S1
        ///A50,20,0,2,1,1,N,&quot;{0}&quot;
        ///B50,50,0,1,2,2,70,B,&quot;{1}&quot;
        ///A100,150,0,4,1,1,N,&quot;{2} &quot;
        ///A160,150,0,4,1,1,N,&quot;{3}&quot;
        ///A140,175,0,1,1,1,N,
        ///P{4}
        ///.
        /// </summary>
        internal static string SampleCode128ELN {
            get {
                return ResourceManager.GetString("SampleCode128ELN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///N
        ///OD
        ///q344
        ///Q192,24
        ///D15
        ///S1
        ///A50,20,0,2,1,1,N,&quot;{0}&quot;
        ///B50,50,0,E30,2,5,80,B,&quot;{1}&quot;
        ///A100,150,0,4,1,1,N,&quot;{2} &quot;
        ///A160,150,0,4,1,1,N,&quot;{3}&quot;
        ///A140,175,0,1,1,1,N,
        ///P{4}
        ///.
        /// </summary>
        internal static string SampleEAN13ELN {
            get {
                return ResourceManager.GetString("SampleEAN13ELN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_icon {
            get {
                object obj = ResourceManager.GetObject("settings_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
