//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodePrinter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodePrinter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto EAN13 / Code 128.
        /// </summary>
        internal static string AutoEAN13Code128 {
            get {
                return ResourceManager.GetString("AutoEAN13Code128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code 128.
        /// </summary>
        internal static string Code128 {
            get {
                return ResourceManager.GetString("Code128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSONE.
        /// </summary>
        internal static string DefaultApplication {
            get {
                return ResourceManager.GetString("DefaultApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN 13.
        /// </summary>
        internal static string EAN13 {
            get {
                return ResourceManager.GetString("EAN13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HelpBarcodePrint {
            get {
                object obj = ResourceManager.GetObject("HelpBarcodePrint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP (10) ITM.ITEMID AS ITEM_CODE, 
        ///                ITM.ITEMNAME AS ITEM_NAME, 
        ///                BAR.ITEMBARCODE AS CROSS_REFERENCE, 
        ///                &apos;AED&apos; AS CURRENCY, 
        ///                 ITM.SALESPRICEINCLTAX SALESPRICEINCLTAX
        ///FROM RETAILITEM ITM
        ///     INNER JOIN INVENTITEMBARCODE BAR ON ITM.ITEMID = BAR.ITEMID
        ///WHERE ITM.DELETED = 0
        ///      AND (UPPER(REPLACE(ITM.ITEMID, &apos;-&apos;, &apos;&apos;)) LIKE UPPER(@ITEMID)
        ///           OR UPPER(BAR.ITEMBARCODE) LIKE UPPER(@ITEMBARCODE))
        ///ORDER BY ITEM_CODE.
        /// </summary>
        internal static string LSOneItemQuery {
            get {
                return ResourceManager.GetString("LSOneItemQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP (10) ITM.[No_] AS                                                                                      ITEM_CODE ,
        ///                ITM.[Description] AS                                                                              ITEM_NAME ,
        ///                BAR.[Barcode No_] AS                                                                              CROSS_REFERENCE ,
        ///                sto.[Currency Code] AS                                                                                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NAVItemQuery {
            get {
                return ResourceManager.GetString("NAVItemQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///N
        ///OD
        ///q344
        ///Q192,24
        ///D15
        ///S1
        ///A40,0,0,3,1,1,N,&quot;$itemid$&quot;
        ///A40,30,0,2,1,1,N,&quot;$description1$&quot;
        ///A40,60,0,2,1,1,N,&quot;$description2$&quot;
        ///B50,90,0,1,2,2,50,B,&quot;$barcode$&quot;
        ///P$count$,1
        ///.
        /// </summary>
        internal static string SampleCode128ELN {
            get {
                return ResourceManager.GetString("SampleCode128ELN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///N
        ///OD
        ///q344
        ///Q192,24
        ///D15
        ///S1
        ///A40,5,0,3,1,1,N,&quot;$itemid$&quot;
        ///A40,35,0,2,1,1,N,&quot;$description1$&quot;
        ///A40,65,0,2,1,1,N,&quot;$description2$&quot;
        ///B50,95,0,E30,2,5,60,B,&quot;$barcode$&quot;
        ///P$count$,1
        ///.
        /// </summary>
        internal static string SampleEAN13ELN {
            get {
                return ResourceManager.GetString("SampleEAN13ELN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_icon {
            get {
                object obj = ResourceManager.GetObject("settings_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
